'------------------------------------------------------------------------------
' <auto-generated>
'     Questo codice è stato generato da uno strumento.
'
'     Le modifiche apportate a questo file possono causare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ForgotPassword


    '''<summary>
    '''Controllo loginForm.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents loginForm As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''Controllo ErrorMessage.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents ErrorMessage As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''Controllo FailureText.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents FailureText As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Controllo Email.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents Email As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controllo DisplayEmail.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents DisplayEmail As Global.System.Web.UI.WebControls.PlaceHolder
End Class
