'------------------------------------------------------------------------------
' <auto-generated>
'     Questo codice è stato generato da uno strumento.
'
'     Le modifiche apportate a questo file possono causare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Manage

    ''' <summary>
    ''' Comando SuccessMessagePlaceHolder.
    ''' </summary>
    ''' <remarks>
    ''' Campo generato automaticamente.
    ''' Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    ''' </remarks>
    Protected WithEvents SuccessMessagePlaceHolder As Global.System.Web.UI.WebControls.PlaceHolder

    ''' <summary>
    ''' Controllo ChangePassword.
    ''' </summary>
    ''' <remarks>
    ''' Campo generato automaticamente.
    ''' Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    ''' </remarks>
    Protected WithEvents ChangePassword As Global.System.Web.UI.WebControls.HyperLink

    ''' <summary>
    ''' Controllo CreatePassword.
    ''' </summary>
    ''' <remarks>
    ''' Campo generato automaticamente.
    ''' Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    ''' </remarks>
    Protected WithEvents CreatePassword As Global.System.Web.UI.WebControls.HyperLink

    ''' <summary>
    ''' Controllo PhoneNumber.
    ''' </summary>
    ''' <remarks>
    ''' Campo generato automaticamente.
    ''' Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    ''' </remarks>
    Protected WithEvents PhoneNumber As Global.System.Web.UI.WebControls.Label
    
End Class
